name: Puppet Build
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Ballerina
        run: sudo apt install ballerina

      - name: Ballerina project build
        run: cd puppet && bal build
